const React = require("react-native");
const { StyleSheet, Dimensions } = React;

const screenHeight = Dimensions.get('window').height;
const screenWidth = Dimensions.get('window').width;

const styles = StyleSheet.create({
    container: {
        justifyContent: 'space-around',
        backgroundColor: '#f7f6f0',
        height: screenHeight+70
    },
    bgImage: {
        flex: 1,
        marginHorizontal: -20,
    },
    section: {
        height: 250,
        paddingHorizontal: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    sectionLarge: {
        height: 250,
        justifyContent: 'space-around',
    },
    sectionHeader: {
        marginBottom: 8,
    },
    priceContainer: {
        alignItems: 'center',
    },
    description: {
        padding: 15,
        lineHeight: 25,
    },
    titleDescription: {
        color: '#19e7f7',
        textAlign: 'center',
        // fontFamily: fonts.primaryRegular,
        fontSize: 15,
    },
    title: {
        marginTop: 30,
    },
    price: {
        marginBottom: 5,
    },
    priceLink: {
        width: "60%",
        borderRadius: 15,
        height: 50,
        alignItems: "center",
        justifyContent: "center",
        marginTop: 40,
        backgroundColor: "#fff",
        color: "#000",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3, },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
    },
    logoText: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#000'
    },
    loginBox: {
        height: 350,
        margin: 20,
        marginTop: -30,
        padding: 10,
        borderRadius: 20,
        backgroundColor: "#fff",
        // width: screenWidth - 30,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3, },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 8,
    },
    Box: {
        height: 550,
        margin: 20,
        marginTop: -30,
        padding: 10,
        borderRadius: 20,
        backgroundColor: "#fff",
        // width: screenWidth - 30,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3, },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 8,
    },
    ProfileBox: {
        height: 150,
        margin: 10,
        marginTop: 1,
        padding: 15,
        borderRadius: 15,
        backgroundColor: "#486fe4",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3, },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
    },
    Label: {
        padding: 5,
        fontSize: 12,
        color: '#fff'
    },
    TextInput: {
        height: 40,
        margin: 10,
        padding: 5,
        fontSize: 14,
        borderRadius: 10,
        backgroundColor: '#fff',
        borderColor: "#fff",
        color: '#000',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3, },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
    },
    LabelBox: {
        height: 40,
        margin: 5,
        fontSize: 14,
        borderRadius: 10,
        backgroundColor: '#fff',
        borderColor: "#fff",
        color: '#000',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3, },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
    },
    signature: {
        flex: 1,
        width: '100%',
        height: '100%',
        borderColor: '#000',
        borderWidth: 1,
    },
    TextInput2: {
        padding: 5,
        fontSize: 18,
        borderBottomWidth: 1,
        borderColor: "#3399CC",
        color: '#000'
    },
    loginFormView: {
        flexDirection: 'row-reverse',
        paddingLeft: 40,
        marginTop: 100,
    },
    scrollView: {
        marginHorizontal: 2,
    },
    inputView: {
        marginBottom: 30
    },
    backgroundImage: {
        width: '100%',
        height: '100%',
        overflow: 'hidden',
        justifyContent: "center",
        alignItems: "center",
        opacity: 0.9,
        borderRadius: 15
    },
    HeadText: {
        color: '#000',
        fontSize: 20, fontWeight: 'bold', margin: 15
    },
    Btn: {
        width: "70%",
        borderRadius: 20,
        height: 50,
        alignItems: "center",
        justifyContent: "center",
        marginTop: 50,
        backgroundColor: "#486fe4",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3, },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
    },
    buttonStyle: {
        flex: 1, justifyContent: "center", alignItems: "center", height: 40,
        backgroundColor: "#cccccc",
        margin: 10
    },
    BtnSearch: {
        width: "50%",
        borderRadius: 25,
        height: 50,
        alignItems: "center",
        justifyContent: "center",
        marginTop: 20,
        backgroundColor: "#486fe4",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3, },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
    },
    BtnDashboard: {
        width: "45%",
        borderRadius: 20,
        height: 50,
        alignItems: "center",
        justifyContent: "center",
        marginTop: 20,
        margin: 10,
        backgroundColor: "#fff",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3, },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
    },
    BtnText: {
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold'
    },
    icon: {
        marginTop: 20,
        margin: 10,
    },
    placeholderStyle: {
        borderTopLeftRadius: 10,
        borderBottomLeftRadius: 10,
        backgroundColor: '#fff',
        fontSize: 14,
        marginLeft: 10,
        marginBottom: 20,
        padding: 10,
        height: 40,
        color: "#000",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3, },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
    },
    selectedTextStyle: {
        borderTopLeftRadius: 10,
        borderBottomLeftRadius: 10,
        marginBottom: 20,
        backgroundColor: '#fff',
        fontSize: 14,
        marginLeft: 10,
        padding: 10,
        height: 40,
        color: "#000",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3, },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
    },
    iconStyle: {
        marginBottom: 20,
        borderTopRightRadius: 10,
        borderBottomRightRadius: 10,
        backgroundColor: '#fff',
        width: 30,
        height: 40,
        marginRight: 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3, },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        // elevation: 7,
    },
    inputSearchStyle: {
        height: 50,
        fontSize: 16,
        backgroundColor: 'white',
        color: "#000",
        borderColor: 'blue',
    },
    dropdown: {
        flex: 2,
        color: "#000",
    },
    popup1: {
        flex: 1, justifyContent: 'center', alignItems: 'center', position: 'absolute',
        top: '30%',
        width:screenWidth-30,
        margin:15,
        // left: '35%',
        // marginRight: 30,
        transform: [{ translateX: 0 }, { translateY: -50 }],
        backgroundColor: '#99aef0',//'#014260',
        borderRadius: 10,
        padding: 20,
        elevation: 15, // Adjust the elevation to control the shadow effect
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.5,
        shadowRadius: 3.84,
    },
    popup: {
        flex: 1, 
        // justifyContent: 'center', alignItems: 'center', 
        position: 'absolute',
        top: '40%',
        width:screenWidth-30,
        margin:15,
        transform: [{ translateX: 0 }, { translateY: -50 }],
        backgroundColor: '#99aef0',//'#014260',
        borderRadius: 10,
        padding: 20,
        elevation: 15, // Adjust the elevation to control the shadow effect
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.5,
        shadowRadius: 3.84,
    },
    optionContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 10,
        margin: 10,
    },
    radioIcon: {
        height: 20,
        width: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#000',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 10,
    },
    selectedRadio: {
        height: 10,
        width: 10,
        borderRadius: 5,
        backgroundColor: '#000',
    },
    // Table Format
    tableContainer: {
        borderWidth: 1,
        borderColor: 'black',
        borderRadius: 4,
        padding: 10,
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 5,
    },
    field: {
        color: '#000',
        flex: 1,
    },
    value: {
        color: '#000',
        flex: 1,
        textAlign: 'right',
    },
    SignUpLogoText: {
        fontSize: 22,
        fontWeight: "800",
        marginTop: 30,
        marginBottom: 20,
        textAlign: "center",
        color: "#000",
        margin: 5,
    },
    SignloginBox: {
        height: 430,
        margin: 20,
        marginTop: 20,
        padding: 15,
        borderRadius: 15,
        backgroundColor: "lightblue",
        // width: screenWidth - 30,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3, },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
    }
});
export default styles;